USE [master]
GO

/****** Object:  Database [ISPHaircutCenter]    Script Date: 19/4/2022 12:02:23 AM ******/
CREATE DATABASE [ISPHaircutCenter]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ISPHaircutCenter', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\ISPHaircutCenter.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'ISPHaircutCenter_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\ISPHaircutCenter_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ISPHaircutCenter].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [ISPHaircutCenter] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [ISPHaircutCenter] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [ISPHaircutCenter] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [ISPHaircutCenter] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [ISPHaircutCenter] SET ARITHABORT OFF 
GO

ALTER DATABASE [ISPHaircutCenter] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [ISPHaircutCenter] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [ISPHaircutCenter] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [ISPHaircutCenter] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [ISPHaircutCenter] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [ISPHaircutCenter] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [ISPHaircutCenter] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [ISPHaircutCenter] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [ISPHaircutCenter] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [ISPHaircutCenter] SET  DISABLE_BROKER 
GO

ALTER DATABASE [ISPHaircutCenter] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [ISPHaircutCenter] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [ISPHaircutCenter] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [ISPHaircutCenter] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [ISPHaircutCenter] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [ISPHaircutCenter] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [ISPHaircutCenter] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [ISPHaircutCenter] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [ISPHaircutCenter] SET  MULTI_USER 
GO

ALTER DATABASE [ISPHaircutCenter] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [ISPHaircutCenter] SET DB_CHAINING OFF 
GO

ALTER DATABASE [ISPHaircutCenter] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [ISPHaircutCenter] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [ISPHaircutCenter] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [ISPHaircutCenter] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [ISPHaircutCenter] SET QUERY_STORE = OFF
GO

ALTER DATABASE [ISPHaircutCenter] SET  READ_WRITE 
GO

